[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = []

[phases.build]
cmds = [
  "cd .. && rm -rf node_modules package-lock.json && npm install && npm run build",
  "rm -rf node_modules && npm ci",
  "npx prisma generate"
]

[start]
cmd = "npm start"
