[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = []

[phases.build]
cmds = [
  "cd .. && npm install && npm run build",
  "npm ci",
  "npx prisma generate"
]

[start]
cmd = "npm start"
