[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
cmds = []

[phases.build]
cmds = [
  "cd .. && npm cache clean --force && rm -rf node_modules .npm && npm install && npm run build",
  "npm cache clean --force && rm -rf node_modules .npm && npm ci",
  "npx prisma generate"
]

[start]
cmd = "npm start"
